### ISSUE TITLE
planting seeds doesn't seem to work

### ISSUE THREAD

**Issue by minertestdude** [ac-minetest/basic_machines#31]
Hello. When :
using current version of basic_machines,
using farming:wheat or farming:cotton seeds placed inside regular locked chest,
mover set to reverse=0 or 1, coordinates src1 and src2 point to planting area (node above ground, ground is prepaired),
mover is activated either directly from distributor (mode 1) on top of clock generator or through  detector (mode 1),
it doesn't seem to plant.

expected:
takes seeds from mover:target (points at chest node),
plants seeds to area from src1 to src2, at +1 iteration.

battery present and charged, mover makes no noise and no action.

tried using switch instead, sending signal 1(OFF), 2(ON) to mover; regardless of repeat value, no success.

configuration above can harvest successfully, with only two changes:
detector "node/player/object" field to "farming:wheat_8" or "farming:cotton_8", filter to "1".
mover reverse value is 0.

I can't seem to understand why its not working, very possibly bug. Thank you!

**Comment by ac-minetest** [comment]
My guess is you don't have reverse set to 1. Be careful with activating mover using OFF signal, this changes reverse.

There is help button in mover, if you click, it reads:
    *advanced* You can reverse start/end position by setting reverse nonzero. This is useful for placing stuff  at many locations-planting.

So set reverse to 1, and source1/2 to cover your farm area and target to be your chest. Then it will take seeds from chest and spread them all around your farm.

It will transform them as written in line 72 of https://github.com/ac-minetest/basic_machines/blob/master/mover.lua :
     ["farming:seed_wheat"]="farming:wheat_1"
This is necessary because merely placing the seed won't make it start to grow - this behavior is defined/caused by farming redo mod - correct name of the growing plant is 'farming:wheat_1'.

**Comment by minertestdude** [comment]
Hello rnd (@ac-minetest)! I have double checked it and it doesn't work. Few pictures may say more than words...
https://imgur.com/a/kQ1lZ3l
Thanks!

**Comment by ac-minetest** [comment]
in your example mover is configured to take out of chest and place block outside. But chest can contain many different items so you need to tell it which one you want to take - just write in filter name of item.
